### ISSUE TITLE
[Question] Icon Captcha solving

### ISSUE THREAD

**Issue by Undefined3301** [Vinyzu/Botright#18]
Hi there :)

I can't find any documentation and function related to Icon Captcha (v3 or v4) solving, is it not available yet or I am not searching the right place ? (captcha solving documentations looks down anyways, but few tests scripts are available on the repo, but not for icon captcha)

**Comment by Vinyzu** [comment]
The api method you would call is `await page.solve_geetest()`, as documented in [Botright Documentation](https://github.com/Vinyzu/Botright/blob/main/docs/botright.rst). As you already noticed, the geeTest and reCaptcha Apis are currently not available, because the GeeTest Code is outdated and im still working on the reCaptcha ai.
 If you want, you can build your own icon solver based on my code tho: https://github.com/Vinyzu/Botright/blob/main/botright/modules/geetest_helpers.py#L26

**Comment by Vinyzu** [comment]
Oh sorry, i thought you meant geetest icon task. I haven’t seen this captcha type, therefore i havent coded a solution for it.

**Comment by Vinyzu** [comment]
Closing as help given & inactive.
ReOpen if CaptchaType gets Relevant.
